name: Deploy IaC

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-iac:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Azure CLI
      uses: azure/cli@v1

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Infrastructure
      run: |
        az deployment group create \
          --resource-group ${{ secrets.RESOURCE_GROUP }} \
          --template-file bicep/main.bicep \
          --parameters @bicep/parameters/dev.parameters.json
